### PR TITLE
Add the estimated time of the next rain

### PR DESCRIPTION
**Pull request by oncleben31**
Add `next_rain_date` in the data structure which is a datetime object representing the start of the next estimated rain.

### CODE REVIEW

**Comment by oncleben31** [comment]
Tested in my home assistant branch [new-meteofrance](https://github.com/oncleben31/home-assistant/tree/new-meteofrance)

**Comment by oncleben31** [comment]
Open question, currently I've avoided breaking change. I didn't overwrite the data["next_rain"] key. 
What do you think? other option is to use this key for date and create another key for delay.

**Comment by victorcerutti** [comment]
I think the best is to keep `next_rain` as it is and add the other key `next_rain_date` (could also be next_rain_time or next_rain_datetime) for the new datetime value.

**Comment by oncleben31** [comment]
OK I use the key `next_rain_datetime`

**Pull request merged**
